sensor:
  information:
    name: "Diga di Ridracoli"
    description: "General Sensor Description"
    type: "idro_level"
    queries:
      - "soglia1"
      - "soglia2"
      - "soglia3"
  ethernet:
    port: 11989
    ip: "0.0.0.0"
  registry:
    url: "https://sensor-registry-17633123551.europe-west8.run.app/v0/api/sensor"
    registerPath: '/register'
    shutDownPath: '/shutdown'
    key: "secretKey"
  apiGateway:
    url: "api-gateway-17633123551.europe-west8.run.app"
    port: 3000
  cronjob:
    day_of_week: "0-6"
    hour: "*"
    minute: "*"
