sensor:
  information:
    name: "Gambettola Water Sensor"
    description: "General Sensor Description"
    type: "idro_level"
    queries:
      - "soglia1"
      - "soglia2"
      - "soglia3"
  ethernet:
    port: 1926
    ip: "0.0.0.0"
  registry:
    url: "http://127.0.0.1:3000/v0/sensor"
    registerPath: '/register'
    shutDownPath: '/shutdown'
    key: "secretKey"
  apiGateway:
    url: "endpoint that receives my data"
    port: 4001
  cronjob:
    day_of_week: "0-6"
    hour: "*"
    minute: "1"
