sensor:
  information:
    name: "Diga di Ridracoli"
    description: "General Sensor Description"
    type: "idro_level"
    queries:
      - "soglia1"
      - "soglia2"
      - "soglia3"
  ethernet:
    port: 11989
    ip: "0.0.0.0"
  registry:
    url: "http://127.0.0.1:3000/v0/api/sensor"
    registerPath: '/register'
    shutDownPath: '/shutdown'
    key: "secretKey"
  apiGateway:
    url: "localhost"
    port: 3000
  cronjob:
    day_of_week: "0-6"
    hour: "*"
    minute: "1"
